name: flutter_cameraview
description: A Flutter plugin for Android and iOS allowing access to the device cameras, a bit deeper!!
version: 0.0.1
author: Herizo Ramaroson
homepage:  https://github.com/hramaroson/flutter_cameraview

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.6.2
  path_provider: ^0.5.0+1 
  sprintf: ^4.0.2 

flutter:
  plugin:
    androidPackage: io.github.hramaroson.fluttercameraview
    pluginClass: FlutterCameraViewPlugin
